apiVersion: v1
kind: Service
metadata:
  name: cluster-baremetal-webhook-service
  namespace: openshift-machine-api
  labels:
    k8s-app: cluster-baremetal-operator
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    k8s-app: cluster-baremetal-operator
  sessionAffinity: None
  type: ClusterIP
