apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAMEPREFIX}-ironic
spec:
  template:
    spec:
      containers:
      - name: ironic-api
        volumeMounts:
        - name: ironic-rpc-auth-config
          mountPath: "/auth/ironic-rpc"
          readOnly: true
        envFrom:
        - configMapRef:
            name: ironic-htpasswd
        - configMapRef:
            name: ironic-bmo-configmap
      - name: ironic-conductor
        volumeMounts:
        - name: ironic-inspector-auth-config
          mountPath: "/auth/ironic-inspector"
          readOnly: true
        - name: ironic-rpc-auth-config
          mountPath: "/auth/ironic-rpc"
          readOnly: true
        envFrom:
        - configMapRef:
            name: ironic-htpasswd
        - configMapRef:
            name: ironic-bmo-configmap
      - name: ironic-inspector
        volumeMounts:
        - name: ironic-auth-config
          mountPath: "/auth/ironic"
          readOnly: true
        envFrom:
        - configMapRef:
            name: ironic-inspector-htpasswd
        - configMapRef:
            name: ironic-bmo-configmap
      volumes:
      - name: ironic-auth-config
        secret:
          secretName: ironic-auth-config
      - name: ironic-inspector-auth-config
        secret:
          secretName: ironic-inspector-auth-config
      - name: ironic-rpc-auth-config
        secret:
          secretName: ironic-rpc-auth-config